version: '3.8'

services:
  pg_database:
    container_name: pg_database
    image: postgres:16.1-alpine3.19
    volumes:
      - ./_scripts/configure.sql:/docker-entrypoint-initdb.d/configure.sql   # Monta um volume com os scripts SQL
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "300MB"

  dev_bank_api_1:
    container_name: dev_bank_api_1
    image: dev_bank_with_drogon_framework:latest
    depends_on:
      - pg_database
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"

  dev_bank_api_2:
    container_name: dev_bank_api_2
    image: dev_bank_with_drogon_framework:latest
    depends_on:
      - pg_database
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"


  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./_nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dev_bank_api_1
      - dev_bank_api_2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"